package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/md5"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/calebhabesh/file-sync/internal/network"
)

const (
	PackageVersion = "1.0.0"
	PackageRelease = "1"
	PackageName    = "filesync"
	FixedTimestamp = 1790208000 // 2026-09-23T00:00:00Z for reproducible builds
)

type ArchInfo struct {
	GoArch  string
	DebArch string
	RpmArch string
	RpmNum  uint16
}

var supportedArchs = []ArchInfo{
	{
		GoArch:  "amd64",
		DebArch: "amd64",
		RpmArch: "x86_64",
		RpmNum:  1,
	},
	{
		GoArch:  "arm64",
		DebArch: "arm64",
		RpmArch: "aarch64",
		RpmNum:  19,
	},
}

// Common terminal assets are generated by the native CLI and shipped in every format.
var terminalAssets = map[string][]byte{}

func loadTerminalAssets(repoRoot, binary string) error {
	for shell, name := range map[string]string{"bash": "bash-completion/completions/orbit", "zsh": "zsh/site-functions/_orbit", "fish": "fish/vendor_completions.d/orbit.fish"} {
		data, err := exec.Command(binary, "orbit", "completion", shell).Output()
		if err != nil {
			return fmt.Errorf("generate %s completion: %w", shell, err)
		}
		terminalAssets[name] = data
	}
	paths, err := filepath.Glob(filepath.Join(repoRoot, "docs/runbooks/*.md"))
	if err != nil {
		return err
	}
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		terminalAssets["doc/filesync/runbooks/"+filepath.Base(path)] = data
	}
	return nil
}

func terminalAssetNames() []string {
	names := make([]string, 0, len(terminalAssets))
	for name := range terminalAssets {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "build_packages error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	repoRoot, err := findRepoRoot()
	if err != nil {
		return err
	}

	distDir := filepath.Join(repoRoot, "dist")
	binDir := filepath.Join(repoRoot, "bin")
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}

	// Embed an explicit source revision; deterministic packaging timestamps stay
	// fixed. Export FILESYNC_BUILD_COMMIT for source archives without Git metadata.
	buildCommit := os.Getenv("FILESYNC_BUILD_COMMIT")
	if buildCommit == "" {
		output, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
		if err != nil {
			return fmt.Errorf("set FILESYNC_BUILD_COMMIT when building an archive without git metadata: %w", err)
		}
		buildCommit = strings.TrimSpace(string(output))
	}
	buildDate := os.Getenv("FILESYNC_BUILD_DATE")
	if buildDate == "" {
		buildDate = "2026-10-01"
	}

	// 1. Build binaries for amd64 and arm64
	for _, arch := range supportedArchs {
		binTarget := filepath.Join(binDir, fmt.Sprintf("filesync-linux-%s", arch.GoArch))
		if arch.GoArch == "amd64" {
			binTarget = filepath.Join(binDir, "filesync")
		}

		fmt.Printf("Building binary for linux/%s -> %s\n", arch.GoArch, binTarget)
		cmd := exec.Command("go", "build", "-trimpath",
			"-ldflags", fmt.Sprintf("-X main.version=%s -X main.commit=%s -X main.date=%s", PackageVersion, buildCommit, buildDate),
			"-o", binTarget, "./cmd/filesync")
		cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOOS=linux", "GOARCH="+arch.GoArch)
		cmd.Dir = repoRoot
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("compile %s: %w", arch.GoArch, err)
		}
	}

	// Ensure bin/orbit symlink exists in repoRoot/bin
	orbitSymlink := filepath.Join(binDir, "orbit")
	_ = os.Remove(orbitSymlink)
	if err := os.Symlink("filesync", orbitSymlink); err != nil {
		return fmt.Errorf("create bin/orbit symlink: %w", err)
	}

	if err := loadTerminalAssets(repoRoot, filepath.Join(binDir, "filesync")); err != nil {
		return err
	}

	// Read common files
	serviceBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/systemd/filesync.service"))
	if err != nil {
		return err
	}
	orbitServiceBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/systemd/orbit.service"))
	if err != nil {
		orbitServiceBytes = serviceBytes
	}
	desktopBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/desktop/orbit.desktop"))
	if err != nil {
		return err
	}
	iconBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/icons/orbit.svg"))
	if err != nil {
		return err
	}
	installScriptBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/scripts/install.sh"))
	if err != nil {
		return err
	}
	uninstallScriptBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/scripts/uninstall.sh"))
	if err != nil {
		return err
	}
	licenseBytes, err := os.ReadFile(filepath.Join(repoRoot, "LICENSE"))
	if err != nil {
		licenseBytes = []byte("MIT License\n")
	}
	noticeBytes, err := os.ReadFile(filepath.Join(repoRoot, "NOTICE"))
	if err != nil {
		return err
	}
	licensesMdBytes, err := os.ReadFile(filepath.Join(repoRoot, "packaging/LICENSES.md"))
	if err != nil {
		return err
	}
	readmeBytes, err := os.ReadFile(filepath.Join(repoRoot, "README.md"))
	if err != nil {
		return err
	}

	// Compute embedded asset metadata
	var assetCount int
	var assetDigest string
	distWebDir := filepath.Join(repoRoot, "web/dist")
	if fi, statErr := os.Stat(distWebDir); statErr == nil && fi.IsDir() {
		h := sha256.New()
		_ = filepath.Walk(distWebDir, func(p string, d os.FileInfo, walkErr error) error {
			if walkErr != nil || d.IsDir() {
				return nil
			}
			rel, _ := filepath.Rel(distWebDir, p)
			data, readErr := os.ReadFile(p)
			if readErr != nil {
				return nil
			}
			assetCount++
			h.Write([]byte(rel))
			h.Write(data)
			return nil
		})
		assetDigest = hex.EncodeToString(h.Sum(nil))
	}

	// Ordinary packages carry the signed release profile compiled into the
	// binary. Refuse to package one that is invalid or expires within 30 days:
	// devices need time to receive the next epoch before this one lapses.
	packaged, err := network.EmbeddedProfile()
	if err != nil {
		return fmt.Errorf("packaged release profile invalid: %w", err)
	}
	packagedDigest, err := packaged.Digest()
	if err != nil {
		return err
	}
	packagedExpires := time.Unix(int64(packaged.Profile.Expires), 0).UTC()
	if time.Until(packagedExpires) < 30*24*time.Hour {
		return fmt.Errorf("packaged release profile expires %s; sign and package the next epoch first (docs/orbit-net-operator.md)", packagedExpires.Format(time.RFC3339))
	}

	manifestData := map[string]any{
		"product":                  "Orbit",
		"version":                  PackageVersion,
		"release":                  PackageRelease,
		"commit":                   buildCommit,
		"built":                    buildDate,
		"schema_version":           13,
		"config_format_version":    1,
		"pure_go_sqlite":           true,
		"node_runtime_required":    false,
		"browser_runtime_required": false,
		"ordinary_entry":           "terminal",
		"legacy_browser_entry":     "orbit legacy-browser",
		"embedded_assets": map[string]any{
			"total_files":   assetCount,
			"digest_sha256": assetDigest,
		},
		"packaged_profile": map[string]any{
			"operator":  packaged.Profile.Operator,
			"authority": packaged.Authority,
			"epoch":     uint64(packaged.Profile.Epoch),
			"expires":   packagedExpires.Format(time.RFC3339),
			"digest":    packagedDigest,
		},
		"license": "MIT",
	}
	manifestBytes, err := json.MarshalIndent(manifestData, "", "  ")
	if err != nil {
		return err
	}
	manifestBytes = append(manifestBytes, '\n')
	manifestPath := filepath.Join(distDir, "release-manifest.json")
	if err := os.WriteFile(manifestPath, manifestBytes, 0o644); err != nil {
		return err
	}

	var generatedPackages []string

	for _, arch := range supportedArchs {
		binPath := filepath.Join(binDir, fmt.Sprintf("filesync-linux-%s", arch.GoArch))
		if arch.GoArch == "amd64" {
			binPath = filepath.Join(binDir, "filesync")
		}
		binBytes, err := os.ReadFile(binPath)
		if err != nil {
			return fmt.Errorf("read binary %s: %w", binPath, err)
		}

		// A. Build tar.gz package (filesync and orbit)
		tarGzName := fmt.Sprintf("%s-v%s-linux-%s.tar.gz", PackageName, PackageVersion, arch.GoArch)
		tarGzPath := filepath.Join(distDir, tarGzName)
		fmt.Printf("Generating %s...\n", tarGzName)
		if err := buildTarGz(tarGzPath, binBytes, serviceBytes, orbitServiceBytes, desktopBytes, iconBytes,
			installScriptBytes, uninstallScriptBytes, licenseBytes, noticeBytes, licensesMdBytes, readmeBytes, manifestBytes); err != nil {
			return fmt.Errorf("build tar.gz for %s: %w", arch.GoArch, err)
		}
		generatedPackages = append(generatedPackages, tarGzPath)

		// Create matching orbit-v...tar.gz
		orbitTarGzName := fmt.Sprintf("orbit-v%s-linux-%s.tar.gz", PackageVersion, arch.GoArch)
		orbitTarGzPath := filepath.Join(distDir, orbitTarGzName)
		tarData, err := os.ReadFile(tarGzPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(orbitTarGzPath, tarData, 0o644); err != nil {
			return err
		}
		generatedPackages = append(generatedPackages, orbitTarGzPath)

		// B. Build .deb package
		debName := fmt.Sprintf("%s_%s_%s.deb", PackageName, PackageVersion, arch.DebArch)
		debPath := filepath.Join(distDir, debName)
		fmt.Printf("Generating %s...\n", debName)
		if err := buildDeb(debPath, arch.DebArch, binBytes, serviceBytes, desktopBytes, iconBytes,
			licenseBytes, noticeBytes, licensesMdBytes, manifestBytes); err != nil {
			return fmt.Errorf("build deb for %s: %w", arch.DebArch, err)
		}
		generatedPackages = append(generatedPackages, debPath)

		// C. Build .rpm package
		rpmName := fmt.Sprintf("%s-%s-%s.%s.rpm", PackageName, PackageVersion, PackageRelease, arch.RpmArch)
		rpmPath := filepath.Join(distDir, rpmName)
		fmt.Printf("Generating %s...\n", rpmName)
		if err := buildRpm(rpmPath, arch, binBytes, serviceBytes, orbitServiceBytes, desktopBytes, iconBytes,
			licenseBytes, noticeBytes, licensesMdBytes, manifestBytes); err != nil {
			return fmt.Errorf("build rpm for %s: %w", arch.RpmArch, err)
		}
		generatedPackages = append(generatedPackages, rpmPath)
	}

	// Include release-manifest.json in generated artifacts
	generatedPackages = append(generatedPackages, manifestPath)

	// 5. Generate SHA256SUMS
	fmt.Println("Generating SHA256SUMS...")
	sumsPath := filepath.Join(distDir, "SHA256SUMS")
	var sumsBuf bytes.Buffer
	for _, p := range generatedPackages {
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		h := sha256.Sum256(data)
		fmt.Fprintf(&sumsBuf, "%s  %s\n", hex.EncodeToString(h[:]), filepath.Base(p))
	}
	if err := os.WriteFile(sumsPath, sumsBuf.Bytes(), 0o644); err != nil {
		return err
	}

	fmt.Println("Release packaging complete! Generated artifacts:")
	for _, p := range generatedPackages {
		fi, _ := os.Stat(p)
		fmt.Printf("  - %s (%d bytes)\n", filepath.Base(p), fi.Size())
	}
	fmt.Printf("  - SHA256SUMS\n")

	return nil
}

func buildTarGz(outPath string, bin, service, orbitService, desktop, icon, installScript, uninstallScript, license, notice, licensesMd, readme, manifest []byte) error {
	f, err := os.OpenFile(outPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()

	gw := gzip.NewWriter(f)
	defer gw.Close()

	tw := tar.NewWriter(gw)
	defer tw.Close()

	fixedTime := time.Unix(FixedTimestamp, 0).UTC()

	entries := []struct {
		Name     string
		Mode     int64
		Typeflag byte
		Linkname string
		Data     []byte
	}{
		{Name: "filesync", Mode: 0755, Typeflag: tar.TypeReg, Data: bin},
		{Name: "orbit", Mode: 0755, Typeflag: tar.TypeSymlink, Linkname: "filesync"},
		{Name: "systemd/filesync.service", Mode: 0644, Typeflag: tar.TypeReg, Data: service},
		{Name: "systemd/orbit.service", Mode: 0644, Typeflag: tar.TypeSymlink, Linkname: "filesync.service"},
		{Name: "desktop/orbit.desktop", Mode: 0644, Typeflag: tar.TypeReg, Data: desktop},
		{Name: "icons/orbit.svg", Mode: 0644, Typeflag: tar.TypeReg, Data: icon},
		{Name: "install.sh", Mode: 0755, Typeflag: tar.TypeReg, Data: installScript},
		{Name: "uninstall.sh", Mode: 0755, Typeflag: tar.TypeReg, Data: uninstallScript},
		{Name: "LICENSE", Mode: 0644, Typeflag: tar.TypeReg, Data: license},
		{Name: "NOTICE", Mode: 0644, Typeflag: tar.TypeReg, Data: notice},
		{Name: "LICENSES.md", Mode: 0644, Typeflag: tar.TypeReg, Data: licensesMd},
		{Name: "README.md", Mode: 0644, Typeflag: tar.TypeReg, Data: readme},
		{Name: "release-manifest.json", Mode: 0644, Typeflag: tar.TypeReg, Data: manifest},
	}

	for _, name := range terminalAssetNames() {
		entries = append(entries, struct {
			Name     string
			Mode     int64
			Typeflag byte
			Linkname string
			Data     []byte
		}{Name: "share/" + name, Mode: 0644, Typeflag: tar.TypeReg, Data: terminalAssets[name]})
	}

	for _, e := range entries {
		hdr := &tar.Header{
			Name:     e.Name,
			Mode:     e.Mode,
			Size:     int64(len(e.Data)),
			ModTime:  fixedTime,
			Uid:      0,
			Gid:      0,
			Uname:    "root",
			Gname:    "root",
			Format:   tar.FormatPAX,
			Typeflag: e.Typeflag,
			Linkname: e.Linkname,
		}
		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}
		if len(e.Data) > 0 {
			if _, err := tw.Write(e.Data); err != nil {
				return err
			}
		}
	}
	return nil
}

func buildDeb(outPath string, debArch string, bin, service, desktop, icon, license, notice, licensesMd, manifest []byte) error {
	fixedTime := time.Unix(FixedTimestamp, 0).UTC()

	// 1. control.tar.gz
	var controlBuf bytes.Buffer
	cgz := gzip.NewWriter(&controlBuf)
	ctw := tar.NewWriter(cgz)

	installedSize := (len(bin)*2 + len(service)*2 + len(desktop) + len(icon) + len(license) + len(notice) + len(licensesMd) + len(manifest)) / 1024
	controlContent := fmt.Sprintf(`Package: %s
Version: %s
Section: utils
Priority: optional
Architecture: %s
Maintainer: File Sync Maintainers <maintainers@example.com>
Installed-Size: %d
Description: Orbit Personal File Manager and File Sync daemon
 Orbit is a personal file manager and synchronization engine over trusted
 Linux replicas, providing SQLite-backed causal history tracking, terminal
 management, desktop integration, and crash-resilient publication.
`, PackageName, PackageVersion, debArch, installedSize)

	prermContent := `#!/bin/sh
set -e
if [ "${1:-}" = remove ] || [ "${1:-}" = deconfigure ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --user stop filesync.service orbit.service 2>/dev/null || true
        systemctl --user disable filesync.service orbit.service 2>/dev/null || true
    fi
fi
exit 0
`

	postinstContent := `#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload 2>/dev/null || true
    if systemctl --user is-active --quiet filesync.service 2>/dev/null; then
        systemctl --user try-restart filesync.service 2>/dev/null || true
    elif systemctl --user is-active --quiet orbit.service 2>/dev/null; then
        systemctl --user try-restart orbit.service 2>/dev/null || true
    fi
fi
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications 2>/dev/null || true
fi
exit 0
`

	postrmContent := `#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload 2>/dev/null || true
fi
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications 2>/dev/null || true
fi
# DATA PRESERVATION GUARANTEE (Invariant S21 / I20):
# Package removal strictly preserves ~/.local/share/filesync, ~/.local/state/filesync,
# ~/.filesync, and all operator workspace folder contents.
exit 0
`

	cEntries := []struct {
		Name string
		Mode int64
		Data []byte
	}{
		{"./control", 0644, []byte(controlContent)},
		{"./prerm", 0755, []byte(prermContent)},
		{"./postinst", 0755, []byte(postinstContent)},
		{"./postrm", 0755, []byte(postrmContent)},
	}

	for _, e := range cEntries {
		hdr := &tar.Header{
			Name:     e.Name,
			Mode:     e.Mode,
			Size:     int64(len(e.Data)),
			ModTime:  fixedTime,
			Format:   tar.FormatPAX,
			Typeflag: tar.TypeReg,
		}
		if err := ctw.WriteHeader(hdr); err != nil {
			return err
		}
		if _, err := ctw.Write(e.Data); err != nil {
			return err
		}
	}
	if err := ctw.Close(); err != nil {
		return err
	}
	if err := cgz.Close(); err != nil {
		return err
	}

	// 2. data.tar.gz
	var dataBuf bytes.Buffer
	dgz := gzip.NewWriter(&dataBuf)
	dtw := tar.NewWriter(dgz)

	dEntries := []struct {
		Name     string
		Mode     int64
		Typeflag byte
		Linkname string
		Data     []byte
	}{
		{Name: "./usr/bin/filesync", Mode: 0755, Typeflag: tar.TypeReg, Data: bin},
		{Name: "./usr/bin/orbit", Mode: 0755, Typeflag: tar.TypeSymlink, Linkname: "filesync"},
		{Name: "./usr/lib/systemd/user/filesync.service", Mode: 0644, Typeflag: tar.TypeReg, Data: service},
		{Name: "./usr/lib/systemd/user/orbit.service", Mode: 0644, Typeflag: tar.TypeSymlink, Linkname: "filesync.service"},
		{Name: "./usr/share/applications/orbit.desktop", Mode: 0644, Typeflag: tar.TypeReg, Data: desktop},
		{Name: "./usr/share/icons/hicolor/scalable/apps/orbit.svg", Mode: 0644, Typeflag: tar.TypeReg, Data: icon},
		{Name: "./usr/share/doc/filesync/copyright", Mode: 0644, Typeflag: tar.TypeReg, Data: license},
		{Name: "./usr/share/doc/filesync/NOTICE", Mode: 0644, Typeflag: tar.TypeReg, Data: notice},
		{Name: "./usr/share/doc/filesync/LICENSES.md", Mode: 0644, Typeflag: tar.TypeReg, Data: licensesMd},
		{Name: "./usr/share/doc/filesync/release-manifest.json", Mode: 0644, Typeflag: tar.TypeReg, Data: manifest},
	}

	for _, name := range terminalAssetNames() {
		dEntries = append(dEntries, struct {
			Name     string
			Mode     int64
			Typeflag byte
			Linkname string
			Data     []byte
		}{Name: "./usr/share/" + name, Mode: 0644, Typeflag: tar.TypeReg, Data: terminalAssets[name]})
	}

	dirs := map[string]bool{}
	for _, e := range dEntries {
		for parent := filepath.Dir(e.Name); parent != "."; parent = filepath.Dir(parent) {
			dirs[parent] = true
		}
	}
	dirNames := make([]string, 0, len(dirs))
	for dir := range dirs {
		dirNames = append(dirNames, dir)
	}
	sort.Strings(dirNames)
	for _, dir := range dirNames {
		if err := dtw.WriteHeader(&tar.Header{Name: dir + "/", Mode: 0755, ModTime: fixedTime, Typeflag: tar.TypeDir}); err != nil {
			return err
		}
	}

	for _, e := range dEntries {
		hdr := &tar.Header{
			Name:     e.Name,
			Mode:     e.Mode,
			Size:     int64(len(e.Data)),
			ModTime:  fixedTime,
			Format:   tar.FormatPAX,
			Typeflag: e.Typeflag,
			Linkname: e.Linkname,
		}
		if err := dtw.WriteHeader(hdr); err != nil {
			return err
		}
		if len(e.Data) > 0 {
			if _, err := dtw.Write(e.Data); err != nil {
				return err
			}
		}
	}
	if err := dtw.Close(); err != nil {
		return err
	}
	if err := dgz.Close(); err != nil {
		return err
	}

	// 3. Assemble ar archive
	debFile, err := os.OpenFile(outPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer debFile.Close()

	if _, err := debFile.WriteString("!<arch>\n"); err != nil {
		return err
	}

	writeArMember := func(name string, data []byte) error {
		hdr := fmt.Sprintf("%-16s%-12d%-6d%-6d%-8o%-10d`\n",
			name, FixedTimestamp, 0, 0, 0100644, len(data))
		if _, err := debFile.WriteString(hdr); err != nil {
			return err
		}
		if _, err := debFile.Write(data); err != nil {
			return err
		}
		if len(data)%2 != 0 {
			if _, err := debFile.Write([]byte("\n")); err != nil {
				return err
			}
		}
		return nil
	}

	if err := writeArMember("debian-binary", []byte("2.0\n")); err != nil {
		return err
	}
	if err := writeArMember("control.tar.gz", controlBuf.Bytes()); err != nil {
		return err
	}
	if err := writeArMember("data.tar.gz", dataBuf.Bytes()); err != nil {
		return err
	}

	return nil
}

func buildRpm(outPath string, arch ArchInfo, bin, service, orbitService, desktop, icon, license, notice, licensesMd, manifest []byte) error {
	// Create CPIO payload (format "070701")
	var cpioBuf bytes.Buffer
	files := []struct {
		Path string
		Mode uint32
		Data []byte
	}{
		{"usr/bin/filesync", 0100755, bin},
		{"usr/bin/orbit", 0120777, []byte("filesync")},
		{"usr/lib/systemd/user/filesync.service", 0100644, service},
		{"usr/lib/systemd/user/orbit.service", 0120777, []byte("filesync.service")},
		{"usr/share/applications/orbit.desktop", 0100644, desktop},
		{"usr/share/icons/hicolor/scalable/apps/orbit.svg", 0100644, icon},
		{"usr/share/doc/filesync/LICENSE", 0100644, license},
		{"usr/share/doc/filesync/NOTICE", 0100644, notice},
		{"usr/share/doc/filesync/LICENSES.md", 0100644, licensesMd},
		{"usr/share/doc/filesync/release-manifest.json", 0100644, manifest},
	}

	for _, name := range terminalAssetNames() {
		files = append(files, struct {
			Path string
			Mode uint32
			Data []byte
		}{"usr/share/" + name, 0100644, terminalAssets[name]})
	}

	for i, f := range files {
		name := f.Path
		hdr := fmt.Sprintf("070701%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x",
			i+1, f.Mode, 0, 0, 1, FixedTimestamp, len(f.Data), 3, 1, 0, 0, len(name)+1, 0)
		cpioBuf.WriteString(hdr)
		cpioBuf.WriteString(name)
		cpioBuf.WriteByte(0)
		for cpioBuf.Len()%4 != 0 {
			cpioBuf.WriteByte(0)
		}
		cpioBuf.Write(f.Data)
		for cpioBuf.Len()%4 != 0 {
			cpioBuf.WriteByte(0)
		}
	}
	// Trailer
	trailerName := "TRAILER!!!"
	trailerHdr := fmt.Sprintf("070701%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x",
		0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, len(trailerName)+1, 0)
	cpioBuf.WriteString(trailerHdr)
	cpioBuf.WriteString(trailerName)
	cpioBuf.WriteByte(0)
	for cpioBuf.Len()%512 != 0 {
		cpioBuf.WriteByte(0)
	}

	// Gzip CPIO
	var gzipPayload bytes.Buffer
	gw := gzip.NewWriter(&gzipPayload)
	gw.Write(cpioBuf.Bytes())
	gw.Close()

	// Build RPM file
	f, err := os.OpenFile(outPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()

	// 1. Lead (96 bytes)
	lead := make([]byte, 96)
	copy(lead[0:4], []byte{0xed, 0xab, 0xee, 0xdb})
	lead[4] = 3
	lead[5] = 0
	binary.BigEndian.PutUint16(lead[6:8], 0) // binary package
	binary.BigEndian.PutUint16(lead[8:10], arch.RpmNum)
	nameField := fmt.Sprintf("%s-%s-%s", PackageName, PackageVersion, PackageRelease)
	copy(lead[10:76], []byte(nameField))
	binary.BigEndian.PutUint16(lead[76:78], 1) // OS: Linux
	binary.BigEndian.PutUint16(lead[78:80], 5) // SigType: RPM_SIG_HEADER
	f.Write(lead)

	// Build main header
	mainHdrBuf := buildRpmMainHeader(arch.RpmArch, files, gzipPayload.Bytes())

	// Build signature header
	sigHdrBuf := buildRpmSigHeader(mainHdrBuf.Bytes(), gzipPayload.Bytes())

	f.Write(sigHdrBuf.Bytes())
	f.Write(mainHdrBuf.Bytes())
	f.Write(gzipPayload.Bytes())

	return nil
}

type rpmIndexEntry struct {
	Tag    uint32
	Type   uint32
	Offset uint32
	Count  uint32
}

func buildRpmSigHeader(header, payload []byte) *bytes.Buffer {
	var data bytes.Buffer
	var entries []rpmIndexEntry

	// Tag 1000: SIGSIZE (size of Header + Payload)
	offset := uint32(data.Len())
	var szBuf [4]byte
	binary.BigEndian.PutUint32(szBuf[:], uint32(len(header)+len(payload)))
	data.Write(szBuf[:])
	entries = append(entries, rpmIndexEntry{
		Tag:    1000,
		Type:   4, // int32
		Offset: offset,
		Count:  1,
	})

	// Package checksums, not publisher signatures. The release SHA256SUMS also
	// binds the complete artifact. RPM verifies these on ordinary installation.
	headerDigest := sha256.Sum256(header)
	headerText := hex.EncodeToString(headerDigest[:]) + "\x00"
	entries = append(entries, rpmIndexEntry{Tag: 273, Type: 6, Offset: uint32(data.Len()), Count: 1})
	data.WriteString(headerText)
	whole := md5.New()
	whole.Write(header)
	whole.Write(payload)
	entries = append(entries, rpmIndexEntry{Tag: 1004, Type: 7, Offset: uint32(data.Len()), Count: 16})
	data.Write(whole.Sum(nil))

	buf := serializeRpmHeader(entries, data.Bytes(), 62)
	for buf.Len()%8 != 0 {
		buf.WriteByte(0)
	}
	return buf
}

func buildRpmMainHeader(rpmArch string, files []struct {
	Path string
	Mode uint32
	Data []byte
}, payload []byte) *bytes.Buffer {
	var data bytes.Buffer
	var entries []rpmIndexEntry

	addString := func(tag uint32, s string) {
		offset := uint32(data.Len())
		data.WriteString(s)
		data.WriteByte(0)
		entries = append(entries, rpmIndexEntry{
			Tag:    tag,
			Type:   6, // string
			Offset: offset,
			Count:  1,
		})
	}

	addStringArray := func(tag uint32, arr []string) {
		offset := uint32(data.Len())
		for _, s := range arr {
			data.WriteString(s)
			data.WriteByte(0)
		}
		entries = append(entries, rpmIndexEntry{
			Tag:    tag,
			Type:   8, // string array
			Offset: offset,
			Count:  uint32(len(arr)),
		})
	}

	addInt32Array := func(tag uint32, arr []uint32) {
		// align 4
		for data.Len()%4 != 0 {
			data.WriteByte(0)
		}
		offset := uint32(data.Len())
		for _, v := range arr {
			var b [4]byte
			binary.BigEndian.PutUint32(b[:], v)
			data.Write(b[:])
		}
		entries = append(entries, rpmIndexEntry{
			Tag:    tag,
			Type:   4, // int32
			Offset: offset,
			Count:  uint32(len(arr)),
		})
	}

	addInt16Array := func(tag uint32, arr []uint16) {
		for data.Len()%2 != 0 {
			data.WriteByte(0)
		}
		offset := uint32(data.Len())
		for _, v := range arr {
			var b [2]byte
			binary.BigEndian.PutUint16(b[:], v)
			data.Write(b[:])
		}
		entries = append(entries, rpmIndexEntry{
			Tag:    tag,
			Type:   3, // int16
			Offset: offset,
			Count:  uint32(len(arr)),
		})
	}

	addString(1000, PackageName)
	addString(1001, PackageVersion)
	addString(1002, PackageRelease)
	addString(1004, "Orbit Personal File Manager and File Sync daemon")
	addString(1005, "Personal file manager and background synchronization agent with SQLite metadata, terminal management and desktop integration.")
	addString(1014, "MIT")
	addString(1016, "Applications/System")
	addString(1021, "linux")
	addString(1022, rpmArch)
	addString(1124, "cpio")
	addString(1125, "gzip")
	addString(1126, "6")
	payloadDigest := sha256.Sum256(payload)
	addStringArray(5092, []string{hex.EncodeToString(payloadDigest[:])})
	addInt32Array(5093, []uint32{8})

	// Lifecycle scripts operate only on the invoking user's manager; privilege,
	// startup enablement and other users' sessions remain explicit operator work.
	addStringArray(1086, []string{"/bin/sh"})
	addString(1024, `#!/bin/sh
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload 2>/dev/null || true
    if systemctl --user is-active --quiet filesync.service 2>/dev/null; then
        systemctl --user try-restart filesync.service 2>/dev/null || true
    elif systemctl --user is-active --quiet orbit.service 2>/dev/null; then
        systemctl --user try-restart orbit.service 2>/dev/null || true
    fi
fi
exit 0
`)
	addStringArray(1087, []string{"/bin/sh"})
	addString(1025, `#!/bin/sh
if [ "${1:-}" = 0 ] && command -v systemctl >/dev/null 2>&1; then
    systemctl --user stop filesync.service orbit.service 2>/dev/null || true
    systemctl --user disable filesync.service orbit.service 2>/dev/null || true
fi
exit 0
`)

	// Post-uninstall script preserving user data
	addStringArray(1088, []string{"/bin/sh"})
	addString(1026, "#!/bin/sh\nif command -v systemctl >/dev/null 2>&1; then systemctl --user daemon-reload 2>/dev/null || true; fi\n# DATA PRESERVATION GUARANTEE (Invariant S21):\n# ~/.local/state/filesync, ~/.filesync and workspace files are strictly preserved\nexit 0\n")

	// File tags
	var baseNames []string
	var dirNames []string
	var dirIndexes []uint32
	var fileSizes []uint32
	var fileModes []uint16
	var fileMD5s []string
	var fileLinks []string
	var fileUsers, fileGroups []string
	var fileFlags, fileTimes []uint32

	dirMap := make(map[string]uint32)
	for _, f := range files {
		dir := "/" + filepath.Dir(f.Path) + "/"
		base := filepath.Base(f.Path)

		dIdx, exists := dirMap[dir]
		if !exists {
			dIdx = uint32(len(dirNames))
			dirNames = append(dirNames, dir)
			dirMap[dir] = dIdx
		}

		baseNames = append(baseNames, base)
		dirIndexes = append(dirIndexes, dIdx)
		fileSizes = append(fileSizes, uint32(len(f.Data)))
		fileModes = append(fileModes, uint16(f.Mode))
		fileUsers = append(fileUsers, "root")
		fileGroups = append(fileGroups, "root")
		fileFlags = append(fileFlags, 0)
		fileTimes = append(fileTimes, FixedTimestamp)
		h := md5.Sum(f.Data)
		if f.Mode&0170000 == 0120000 {
			fileMD5s = append(fileMD5s, "")
			fileLinks = append(fileLinks, string(f.Data))
		} else {
			fileMD5s = append(fileMD5s, hex.EncodeToString(h[:]))
			fileLinks = append(fileLinks, "")
		}
	}

	addStringArray(1117, baseNames)
	addStringArray(1118, dirNames)
	addInt32Array(1116, dirIndexes)
	addInt32Array(1028, fileSizes)
	addInt16Array(1030, fileModes)
	addStringArray(1035, fileMD5s)
	addStringArray(1036, fileLinks)
	addInt32Array(1034, fileTimes)
	addInt32Array(1037, fileFlags)
	addStringArray(1039, fileUsers)
	addStringArray(1040, fileGroups)

	return serializeRpmHeader(entries, data.Bytes(), 63)
}

// Layout follows upstream rpm lib/header.cc and include/rpm/rpmtag.h;
// package-manager transactions, not extraction alone, validate compatibility.
func serializeRpmHeader(entries []rpmIndexEntry, data []byte, regionTag uint32) *bytes.Buffer {
	// Sort entries by Tag as required by RPM spec
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Tag < entries[j].Tag
	})

	// RPM validates monotonic offsets in tag order. Repack values after sorting,
	// retaining each type's alignment rather than merely sorting the indexes.
	var ordered bytes.Buffer
	for i := range entries {
		e := &entries[i]
		start := int(e.Offset)
		length, alignment := 0, 1
		switch e.Type {
		case 3:
			alignment = 2
			length = int(e.Count) * 2
		case 4:
			alignment = 4
			length = int(e.Count) * 4
		case 7:
			length = int(e.Count)
		case 6, 8:
			count := int(e.Count)
			for j := 0; j < count; j++ {
				n := bytes.IndexByte(data[start+length:], 0)
				if n < 0 {
					panic("unterminated generated RPM string")
				}
				length += n + 1
			}
		default:
			panic("unsupported generated RPM type")
		}
		for ordered.Len()%alignment != 0 {
			ordered.WriteByte(0)
		}
		e.Offset = uint32(ordered.Len())
		ordered.Write(data[start : start+length])
	}
	// v4 immutable/signature region: index points to the trailing region record;
	// its negative offset spans the complete index, including the region entry.
	regionOffset := uint32(ordered.Len())
	regionCount := len(entries) + 1
	var trailer [16]byte
	binary.BigEndian.PutUint32(trailer[0:4], regionTag)
	binary.BigEndian.PutUint32(trailer[4:8], 7)
	binary.BigEndian.PutUint32(trailer[8:12], uint32(-int32(regionCount*16)))
	binary.BigEndian.PutUint32(trailer[12:16], 16)
	ordered.Write(trailer[:])
	entries = append([]rpmIndexEntry{{Tag: regionTag, Type: 7, Offset: regionOffset, Count: 16}}, entries...)
	data = ordered.Bytes()

	var buf bytes.Buffer
	buf.Write([]byte{0x8e, 0xad, 0xe8, 0x01}) // Magic
	buf.Write([]byte{0, 0, 0, 0})             // Reserved

	var nindexBuf [4]byte
	binary.BigEndian.PutUint32(nindexBuf[:], uint32(len(entries)))
	buf.Write(nindexBuf[:])

	var nbytesBuf [4]byte
	binary.BigEndian.PutUint32(nbytesBuf[:], uint32(len(data)))
	buf.Write(nbytesBuf[:])

	for _, e := range entries {
		var b [16]byte
		binary.BigEndian.PutUint32(b[0:4], e.Tag)
		binary.BigEndian.PutUint32(b[4:8], e.Type)
		binary.BigEndian.PutUint32(b[8:12], e.Offset)
		binary.BigEndian.PutUint32(b[12:16], e.Count)
		buf.Write(b[:])
	}
	buf.Write(data)

	return &buf
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("repository root containing go.mod not found")
}
