package protocol

import (
	"bytes"
	"encoding/hex"
	"os"
	"strings"
	"testing"
)

func TestWANW08LANIndependentGoldenAndStrictCodec(t *testing.T) {
	// Fixture was independently generated by Python cryptography from seed
	// bytes 00..1f, JSON insertion order and DER SubjectPublicKeyInfo hashing.
	b, err := os.ReadFile("../../schemas/fixtures/lan-v1/announcement.json")
	if err != nil {
		t.Fatal(err)
	}
	var a LANAnnouncement
	if err = NetworkDecode(b, &a); err != nil {
		t.Fatal(err)
	}
	canonical, err := a.Canonical()
	if err != nil {
		t.Fatal(err)
	}
	expectedHex, err := os.ReadFile("../../schemas/fixtures/lan-v1/canonical.hex")
	if err != nil {
		t.Fatal(err)
	}
	expected, err := hex.DecodeString(strings.TrimSpace(string(expectedHex)))
	if err != nil || !bytes.Equal(canonical, expected) {
		t.Fatal("independent canonical bytes", err)
	}
	if err = a.Verify(2000000000); err != nil {
		t.Fatal("independent signature/pin", err)
	}
	for _, body := range [][]byte{append(b, []byte(`{}`)...), []byte(`{"version":"1","version":"1"}`), []byte(strings.Replace(string(b), `"version": "1"`, `"version": "1", "folder": "private"`, 1))} {
		if NetworkDecode(body, &a) == nil {
			t.Fatal("strict decode accepted altered envelope")
		}
	}
}

func TestWANW09LANQUICIndependentGoldenAndCapabilities(t *testing.T) {
	b, err := os.ReadFile("../../schemas/fixtures/lan-quic-v1/announcement.json")
	if err != nil {
		t.Fatal(err)
	}
	var a LANAnnouncement
	if err = NetworkDecode(b, &a); err != nil {
		t.Fatal(err)
	}
	expectedHex, err := os.ReadFile("../../schemas/fixtures/lan-quic-v1/canonical.hex")
	if err != nil {
		t.Fatal(err)
	}
	expected, err := hex.DecodeString(strings.TrimSpace(string(expectedHex)))
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := a.Canonical()
	if err != nil || !bytes.Equal(canonical, expected) {
		t.Fatal("canonical", err)
	}
	if err = a.Verify(2000000000); err != nil {
		t.Fatal("independent UDP pin/signature", err)
	}
	a.Capabilities = a.Capabilities[:1]
	if _, err = a.Canonical(); err == nil {
		t.Fatal("UDP without HTTP3 capability")
	}
}
